version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=diablo
      - MYSQL_ROOT_PASSWORD=diablo
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  backend-api:
    # Use the image built from the Dockerfile in the current directory
    image: node:latest
    env_file:
      - .env
    # Specify the working directory inside the container
    working_dir: /app
    # Mount the current directory into the container for live code editing
    volumes:
      - .:/app
    # Expose the development server port (if needed)
    ports:
      - '3000:3000'
    # Install and run the development server using Yarn
    command:
      - sh
      - -c
      - |
        yarn install
        yarn start:dev
    links:
      - db
    depends_on:
      - db
volumes:
  db:
    driver: local
