version: '3'

services:
  nest:
    image: node:latest
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '${BACKEND_PORT:-3000}:${BACKEND_PORT:-3000}'
    command:
      - sh
      - -c
      - |
        yarn install
        yarn start:dev
    networks:
      - app-network

  # mysql:
  #   image: mysql:5.7
  #   env_file:
  #     - .env
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  #     MYSQL_DATABASE: diablo4trading
  #     MYSQL_USER: ${DATABASE_USERNAME}
  #     MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  #   ports:
  #     - "${DATABASE_PORT}:${DATABASE_PORT}"
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   networks:
  #     - app-network